<?php
 /*****************************************************************************
  * 
  * Only enqueue the index.js in the editor.
  * 
  ****************************************************************************/

add_action( 'enqueue_block_editor_assets', 'myprefix_add_block_styles_editor' );

function myprefix_add_block_styles_editor() {
  if ( ! function_exists( 'register_block_type' ) ) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include( MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename( __DIR__ ) . '/index.asset.php' );    

  wp_enqueue_script(
    'myprefix-block-styles-script',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename( __DIR__ ) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version']
  );
}

 /*****************************************************************************
  * 
  * Only the stylesheet for front- and back -end.
  * 
  ****************************************************************************/

add_action( 'enqueue_block_assets', 'myprefix_add_block_styles' );

function myprefix_add_block_styles() {

  wp_enqueue_style( 
      'myprefix-block-styles-style', 
      MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename( __DIR__ ) .  '/style.css',
      array(),
      filemtime( MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename( __DIR__ ) . '/style.css' )   
  );
}
 
/******************************************************************************
 * 
 * Register block styles. More styles are registered in the JS file.
 * 
 *****************************************************************************/

add_action( 'init', 'myprefix_add_block_register_styles' );

function myprefix_add_block_register_styles() {
  // Use stylesheet registered above
  register_block_style(
      'core/paragraph',
      array(
          'name'  => 'firebrick', // Adds class name .is-style-firebrick
          'label' => __( 'Fire Brick Red', 'textDomain' ),
          'style_handle'=> 'myprefix-block-styles-style'
      )
  );

  // Use inline style
  register_block_style(
      'core/paragraph',
      array(
          'name'         => 'dodgerblue', // Adds class name .is-style-dodgerblue
          'label'        => __( 'Dodger Blue', 'textDomain' ),
          'inline_style' => '.is-style-dodgerblue{ color: dodgerblue; }'
      )
  );

  // This will be removed with PHP below
  register_block_style(
      'core/paragraph',
      array(
          'name'         => 'remove-pink',  // Adds class name is-style-remove-pink
          'label'        => __( 'Removed with php', 'textDomain' ),
          'inline_style' => '.is-style-remove-pink{ color: pink; }'
      )
  );

  // This will be removed with JS
  register_block_style(
      'core/paragraph',
      array(
          'name'         => 'remove-gold', // Adds class name is-style-remove-gold
          'label'        => __( 'Removed with JS', 'textDomain' ),
          'inline_style' => '.is-style-remove-gold{ color: gold; }'
      )
  );

}

/******************************************************************************
 * 
 * Unregister block styles.
 * 
 *****************************************************************************/

add_action('wp_loaded', 'myprefix_unregister_block_styles', 99);

function myprefix_unregister_block_styles() {
  // This one registered above
  unregister_block_style( 'core/paragraph', 'remove-pink' );
  // This will not remove the core/button outline style because core block styles are registered using JS
  // Commented out to stop PHP warning
  //unregister_block_style( 'core/button', 'outline' );
}