<?php

/******************************************************************************
 * 
 * Register the meta field
 * 
 *****************************************************************************/

/**
 * Fetch the meta key from the meta-simple.metafield.json file.
 */
if (file_exists(__DIR__ . '/block-binding-meta-box.metafield.json')) {

  $block_json = file_get_contents('block-binding-meta-box.metafield.json', true);

  $json_array = $block_json
    ? json_decode($block_json, true)
    : false;

  $meta_field = is_array($json_array) && array_key_exists('metaField', $json_array)
    ? $json_array['metaField']
    : 'pants';
} else {
  error_log("ERROR: block-binding-meta-box.metafield.json file not found. Logged from line" . __LINE__ . " in " . __FILE__);
}

// Define a constant to make it easily available across functions
define('MYPREFIX_BLOCK_BINDING_META_BOX_FILED', $meta_field);

/**
 * Register the meta field
 */
add_action('init', 'myprefix_block_binding_meta_box_field');

function myprefix_block_binding_meta_box_field() {
  register_meta(
    'post',
    MYPREFIX_BLOCK_BINDING_META_BOX_FILED,
    array(
      'show_in_rest'       => true,
      'single'             => true,
      'type'               => 'string',
      'default'            => '',
      'label'              => 'Block Binding Meta Box',
      'sanitize_callback'  => 'sanitize_textarea_field',
      'auth_callback'      => function () {
        return current_user_can('edit_posts');
      }
    )
  );
}

/******************************************************************************
 * 
 * Enqueue the script file
 * 
 *****************************************************************************/

add_action('enqueue_block_editor_assets', 'myprefix_block_binding_meta_box');

function myprefix_block_binding_meta_box() {

  if (! function_exists('register_block_type')) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include(MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename(__DIR__) . '/index.asset.php');

  wp_enqueue_script(
    'myprefix-block-binding-meta-box-script',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename(__DIR__) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version']
  );
}
