<?php

/******************************************************************************
 * 
 * Only enqueue the index.js in the editor.
 * 
 *****************************************************************************/

add_action( 'enqueue_block_editor_assets', 'myprefix_variations_existing_blocks_editor' );

function myprefix_variations_existing_blocks_editor() {
  
  if ( ! function_exists( 'register_block_type' ) ) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include( MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename( __DIR__ ) . '/index.asset.php' );

  wp_enqueue_script( 
    'myprefix-variations-existing-blocks-script', 
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename( __DIR__ ) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version']
  );
}

/******************************************************************************
 * 
 * Enqueue the stylesheet
 * 
 *****************************************************************************/

add_action( 'enqueue_block_assets', 'myprefix_variations_existing_blocks' );

function myprefix_variations_existing_blocks() {
  
  if ( ! function_exists( 'register_block_type' ) ) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include( MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename( __DIR__ ) . '/index.asset.php' );

  wp_enqueue_style(
    'myprefix-variations-existing-blocks-style',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename( __DIR__ ) . '/style.css',
    array(),
    $asset_file['version']
  );
}

