<?php

/******************************************************************************
 * 
 * Register the script file
 * 
 *****************************************************************************/

add_action('enqueue_block_editor_assets', 'myprefix_filter_block_settings');

function myprefix_filter_block_settings() {

  if (! function_exists('register_block_type')) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include(MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename(__DIR__) . '/index.asset.php');

  wp_enqueue_script(
    'myprefix-filter-block-settings-script',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename(__DIR__) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version']
  );
}

/******************************************************************************
 * 
 * A filter to limit the heading levels available for the core/heading block
 * 
 *****************************************************************************/

add_filter('register_block_type_args', 'myprefix_modify_heading_levels_globally', 10, 2);

function myprefix_modify_heading_levels_globally($args, $block_type) {

  // Check if the current user is an Administrator.
  $is_administrator = current_user_can('edit_theme_options');

  // Only proceed if the current block is a Heading and the user is not an Administrator.
  /*   if ('core/heading' !== $block_type || $is_administrator) {
    return $args;
  } */

  //OR remove for everyone
  $args['attributes']['levelOptions']['default'] = [3, 4, 5];

  // Disable H1, H5, and H6.
  $args['attributes']['levelOptions']['default'] = [2, 3, 4];

  return $args;
}
