<?php

/******************************************************************************
 * 
 * Register the script file
 * 
 *****************************************************************************/

add_action( 'enqueue_block_editor_assets', 'myprefix_filter_block_settings' );

function myprefix_filter_block_settings() {

  if ( ! function_exists( 'register_block_type' ) ) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include( MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename( __DIR__ ) . '/index.asset.php' );

  wp_enqueue_script(
    'myprefix-filter-block-settings-script',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename( __DIR__ ) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version']
  ); 
}
