<?php

/**
 * Include the PHP filter files.
 */
include 'block-type-metadata-settings.php';
include 'wp-theme-json-data-user.php';
include 'block-editor-settings-all.php';

/**
 * Enqueue the JS file.
 */
add_action('enqueue_block_editor_assets', 'myprefix_block_editor_settings');

function myprefix_block_editor_settings() {

  if (! function_exists('register_block_type')) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include(MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename(__DIR__) . '/index.asset.php');

  wp_enqueue_script(
    'myprefix-block-editor-settings',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename(__DIR__) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version'],
    array('in_footer' => true)
  );
}
