<?php

/****************************************************************************
 * 
 * Register the script file.
 * 
 ****************************************************************************/

add_action('enqueue_block_editor_assets', 'myprefix_block_binding_custom_source');

function myprefix_block_binding_custom_source() {

  if (! function_exists('register_block_type')) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include(MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename(__DIR__) . '/index.asset.php');

  wp_enqueue_script(
    'myprefix-block-binding-custom-source',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename(__DIR__) . '/index.js',
    $asset_file['dependencies'],
    $asset_file['version']
  );
}

/****************************************************************************
 * 
 * Register the block binding source.
 * 
 ****************************************************************************/

add_action('init', 'myprefix_register_binding_sources');

function myprefix_register_binding_sources() {
  register_block_bindings_source('myprefix/bind-post-data', [
    'label'              => __('Bind Post Data', 'myprefix'),
    'get_value_callback' => 'myprefix_bind_post_data_callback',
    'uses_context'       => ['postId'],
  ]);
}

function myprefix_bind_post_data_callback($source_args, $block_instance, $attribute_name) {
  if (! isset($source_args['key'])) {
    return null;
  }

  $post_id = $block_instance->context['postId'] ?? get_the_ID();

  /**
   * Note, each binding `key` in the editor HTML has been set to the correct value 
   * to use with getEditedPostAttribute() in the JS script. That is: `title`, `excerpt` and `permalink`.
   */
  if ('title' === $source_args['key']) {
    return get_post_field('post_title', $post_id);
  } elseif ('excerpt' === $source_args['key']) {
    return get_post_field('post_excerpt', $post_id);
  } elseif ('permalink' === $source_args['key']) {
    return get_permalink($post_id);
  }

  return null;
}

/****************************************************************************
 * 
 * Register the black pattern that uses the block binding.
 * 
 * Note, each binding `key` in the editor HTML has been set to the correct value
 * to use with getEditedPostAttribute() in the JS script. That is: `title`, 
 * `excerpt` and `permalink`.
 * 
 ****************************************************************************/

add_action('init', 'myprefix_bind_custom_source_register_patterns');

function myprefix_bind_custom_source_register_patterns() {
  register_block_pattern('myprefix/bind-post-data', array(
    'title'      => __('Bind post data to a group of blocks', 'myprefix'),
    'description' => __('For testing block binding with custom sources'),
    'categories' => array('posts'),
    'keywords' => array('block binding'),
    'blockTypes' => array('core/heading', 'core/paragraph', 'core/button'),
    'postType'  => array('posts'),
    'content'    => '<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:heading {"placeholder":"Add post title","metadata":{"bindings":{"content":{"source":"myprefix/bind-post-data","args":{"key":"title"}}}}} -->
<h2 class="wp-block-heading"></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"placeholder":"Add post excerpt","metadata":{"bindings":{"content":{"source":"myprefix/bind-post-data","args":{"key":"excerpt"}}}}} -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"metadata":{"bindings":{"url":{"source":"myprefix/bind-post-data","args":{"key":"permalink"}}}}} -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Read post →</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->'
  ));
}
