<?php

add_action( 'enqueue_block_editor_assets', 'myprefix_block_collection' );

function myprefix_block_collection() {
  
  if ( ! function_exists( 'register_block_type' ) ) {
    // Gutenberg is not active.
    return;
  }

  /**
   * Include the assets file, which is generated by wp-scripts
   */
  $asset_file = include( MYPREFIX_GUT_BLOCKS_PLUGIN_PATH . basename( __DIR__ ) . '/index.asset.php' );

  wp_enqueue_script(
    'myprefix-block-collection-script',
    MYPREFIX_GUT_BLOCKS_PLUGIN_URL . basename( __DIR__ ) . '/index.js',
    $asset_file['version'],
    $asset_file['dependencies'],
    true
  ); 
}